/* hamlive-oss — MIT License. See LICENSE. */

export interface ChatEmojiEntry {
    emoji: string;
    name: string;
    keywords: string[];
}

export interface ChatEmojiCategory {
    id: string;
    label: string;
    icon: string;
    emoji: ChatEmojiEntry[];
}

const entries = (items: Array<[string, string, string[]]>): ChatEmojiEntry[] =>
    items.map(([emoji, name, keywords]) => ({ emoji, name, keywords }));

export const CHAT_EMOJI_CATEGORIES: ChatEmojiCategory[] = [
    { id: 'smileys', label: 'Smileys & Emotion', icon: '😀', emoji: entries([
        ['😀', 'grinning', ['face', 'smile', 'happy', 'joy', ':d', 'grin']],
        ['😃', 'smiley', ['face', 'happy', 'joy', 'haha', ':d', ':)', 'smile', 'funny']],
        ['😄', 'smile', ['face', 'happy', 'joy', 'funny', 'haha', 'laugh', 'like', ':d', ':)']],
        ['😁', 'grin', ['face', 'happy', 'smile', 'joy', 'kawaii']],
        ['😆', 'laughing', ['happy', 'joy', 'lol', 'satisfied', 'haha', 'face', 'glad', 'xd', 'laugh']],
        ['😅', 'sweat smile', ['face', 'hot', 'happy', 'laugh', 'sweat', 'smile', 'relief']],
        ['😂', 'joy', ['face', 'cry', 'tears', 'weep', 'happy', 'happytears', 'haha']],
        ['🤣', 'rofl', ['face', 'rolling', 'floor', 'laughing', 'lol', 'haha']],
        ['☺️', 'relaxed', ['face', 'blush', 'massage', 'happiness']],
        ['😊', 'blush', ['face', 'smile', 'happy', 'flushed', 'crush', 'embarrassed', 'shy', 'joy']],
        ['😇', 'innocent', ['face', 'angel', 'heaven', 'halo']],
        ['🙂', 'slightly smiling face', ['face', 'smile']],
        ['🙃', 'upside down face', ['face', 'flipped', 'silly', 'smile']],
        ['😉', 'wink', ['face', 'happy', 'mischievous', 'secret', ';)', 'smile', 'eye']],
        ['😌', 'relieved', ['face', 'relaxed', 'phew', 'massage', 'happiness']],
        ['😍', 'heart eyes', ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart']],
        ['🥰', 'smiling face with three hearts', ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'hearts', 'adore']],
        ['😘', 'kissing heart', ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss']],
        ['😗', 'kissing', ['love', 'like', 'face', '3', 'valentines', 'infatuation', 'kiss']],
        ['😙', 'kissing smiling eyes', ['face', 'affection', 'valentines', 'infatuation', 'kiss']],
        ['😚', 'kissing closed eyes', ['face', 'love', 'like', 'affection', 'valentines', 'infatuation', 'kiss']],
        ['😋', 'yum', ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', 'nom', 'delicious', 'savouring']],
        ['😛', 'stuck out tongue', ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'tongue']],
        ['😝', 'stuck out tongue closed eyes', ['face', 'prank', 'playful', 'mischievous', 'smile', 'tongue']],
        ['😜', 'stuck out tongue winking eye', ['face', 'prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue']],
        ['🤪', 'zany', ['face', 'goofy', 'crazy']],
        ['🤨', 'raised eyebrow', ['face', 'distrust', 'scepticism', 'disapproval', 'disbelief', 'surprise']],
        ['🧐', 'monocle', ['face', 'stuffy', 'wealthy']],
        ['🤓', 'nerd face', ['face', 'nerdy', 'geek', 'dork']],
        ['😎', 'sunglasses', ['face', 'cool', 'smile', 'summer', 'beach', 'sunglass']],
        ['🤩', 'star struck', ['face', 'smile', 'starry', 'eyes', 'grinning']],
        ['🥳', 'partying', ['face', 'celebration', 'woohoo']],
        ['😏', 'smirk', ['face', 'smile', 'mean', 'prank', 'smug', 'sarcasm']],
        ['😒', 'unamused', ['indifference', 'bored', 'straight face', 'serious', 'sarcasm', 'unimpressed', 'skeptical', 'dubious', 'side eye']],
        ['😞', 'disappointed', ['face', 'sad', 'upset', 'depressed', ':(']],
        ['😔', 'pensive', ['face', 'sad', 'depressed', 'upset']],
        ['😟', 'worried', ['face', 'concern', 'nervous', ':(']],
        ['😕', 'confused', ['face', 'indifference', 'huh', 'weird', 'hmmm', ':/']],
        ['🙁', 'slightly frowning face', ['face', 'frowning', 'disappointed', 'sad', 'upset']],
        ['☹', 'frowning face', ['face', 'sad', 'upset', 'frown']],
        ['😣', 'persevere', ['face', 'sick', 'no', 'upset', 'oops']],
        ['😖', 'confounded', ['face', 'confused', 'sick', 'unwell', 'oops', ':s']],
        ['😫', 'tired face', ['sick', 'whine', 'upset', 'frustrated']],
        ['😩', 'weary', ['face', 'tired', 'sleepy', 'sad', 'frustrated', 'upset']],
        ['🥺', 'pleading', ['face', 'begging', 'mercy']],
        ['😢', 'cry', ['face', 'tears', 'sad', 'depressed', 'upset', ':\'(']],
        ['😭', 'sob', ['face', 'cry', 'tears', 'sad', 'upset', 'depressed']],
        ['😤', 'triumph', ['face', 'gas', 'phew', 'proud', 'pride']],
        ['😠', 'angry', ['mad', 'face', 'annoyed', 'frustrated']],
        ['😡', 'rage', ['angry', 'mad', 'hate', 'despise']],
        ['🤬', 'symbols over mouth', ['face', 'swearing', 'cursing', 'cussing', 'profanity', 'expletive']],
        ['🤯', 'exploding head', ['face', 'shocked', 'mind', 'blown']],
        ['😳', 'flushed', ['face', 'blush', 'shy', 'flattered']],
        ['🥵', 'hot', ['face', 'feverish', 'heat', 'red', 'sweating']],
        ['🥶', 'cold', ['face', 'blue', 'freezing', 'frozen', 'frostbite', 'icicles']],
        ['😱', 'scream', ['face', 'munch', 'scared', 'omg']],
        ['😨', 'fearful', ['face', 'scared', 'terrified', 'nervous', 'oops', 'huh']],
        ['😰', 'cold sweat', ['face', 'nervous', 'sweat']],
        ['😥', 'disappointed relieved', ['face', 'phew', 'sweat', 'nervous']],
        ['😓', 'sweat', ['face', 'hot', 'sad', 'tired', 'exercise']],
        ['🤗', 'hugs', ['face', 'smile', 'hug']],
        ['🤔', 'thinking', ['face', 'hmmm', 'think', 'consider']],
        ['🤭', 'hand over mouth', ['face', 'whoops', 'shock', 'surprise']],
        ['🤫', 'shushing', ['face', 'quiet', 'shhh']],
        ['🤥', 'lying face', ['face', 'lie', 'pinocchio']],
        ['😶', 'no mouth', ['face', 'hellokitty']],
        ['😐', 'neutral face', ['indifference', 'meh', ':|', 'neutral']],
        ['😑', 'expressionless', ['face', 'indifferent', '- -', 'meh', 'deadpan']],
        ['😬', 'grimacing', ['face', 'grimace', 'teeth']],
        ['🙄', 'roll eyes', ['face', 'eyeroll', 'frustrated']],
        ['😯', 'hushed', ['face', 'woo', 'shh']],
        ['😦', 'frowning', ['face', 'aw', 'what']],
        ['😧', 'anguished', ['face', 'stunned', 'nervous']],
        ['😮', 'open mouth', ['face', 'surprise', 'impressed', 'wow', 'whoa', ':o']],
        ['😲', 'astonished', ['face', 'xox', 'surprised', 'poisoned']],
        ['😴', 'sleeping', ['face', 'tired', 'sleepy', 'night', 'zzz']],
        ['🤤', 'drooling face', ['face']],
        ['😪', 'sleepy', ['face', 'tired', 'rest', 'nap']],
        ['😵', 'dizzy face', ['spent', 'unconscious', 'xox', 'dizzy']],
        ['🤐', 'zipper mouth face', ['face', 'sealed', 'zipper', 'secret']],
        ['🥴', 'woozy', ['face', 'dizzy', 'intoxicated', 'tipsy', 'wavy']],
        ['🤢', 'nauseated face', ['face', 'vomit', 'gross', 'green', 'sick', 'throw up', 'ill']],
        ['🤮', 'vomiting', ['face', 'sick']],
        ['🤧', 'sneezing face', ['face', 'gesundheit', 'sneeze', 'sick', 'allergy']],
        ['😷', 'mask', ['face', 'sick', 'ill', 'disease']],
        ['🤒', 'face with thermometer', ['sick', 'temperature', 'thermometer', 'cold', 'fever']],
        ['🤕', 'face with head bandage', ['injured', 'clumsy', 'bandage', 'hurt']],
        ['🤑', 'money mouth face', ['face', 'rich', 'dollar', 'money']],
        ['🤠', 'cowboy hat face', ['face', 'cowgirl', 'hat']],
        ['😈', 'smiling imp', ['devil', 'horns']],
        ['👿', 'imp', ['devil', 'angry', 'horns']],
        ['👹', 'japanese ogre', ['monster', 'red', 'mask', 'halloween', 'scary', 'creepy', 'devil', 'demon', 'japanese', 'ogre']],
        ['👺', 'japanese goblin', ['red', 'evil', 'mask', 'monster', 'scary', 'creepy', 'japanese', 'goblin']],
        ['🤡', 'clown face', ['face']],
        ['💩', 'poop', ['hankey', 'shitface', 'fail', 'turd', 'shit']],
        ['👻', 'ghost', ['halloween', 'spooky', 'scary']],
        ['💀', 'skull', ['dead', 'skeleton', 'creepy', 'death']],
        ['👽', 'alien', ['ufo', 'paul', 'weird', 'outer space']],
        ['🤖', 'robot', ['computer', 'machine', 'bot']],
        ['😺', 'smiley cat', ['animal', 'cats', 'happy', 'smile']],
        ['😸', 'smile cat', ['animal', 'cats', 'smile']],
        ['😹', 'joy cat', ['animal', 'cats', 'haha', 'happy', 'tears']],
        ['😻', 'heart eyes cat', ['animal', 'love', 'like', 'affection', 'cats', 'valentines', 'heart']],
        ['😼', 'smirk cat', ['animal', 'cats', 'smirk']],
        ['😽', 'kissing cat', ['animal', 'cats', 'kiss']],
        ['🙀', 'scream cat', ['animal', 'cats', 'munch', 'scared', 'scream']],
        ['😿', 'crying cat face', ['animal', 'tears', 'weep', 'sad', 'cats', 'upset', 'cry']],
        ['😾', 'pouting cat', ['animal', 'cats']],
        ['㊗️', 'congratulations', ['chinese', 'kanji', 'japanese', 'red-circle']],
        ['🈴', 'u5408', ['japanese', 'chinese', 'join', 'kanji', 'red-square']],
        ['🈵', 'u6e80', ['full', 'chinese', 'japanese', 'red-square', 'kanji']],
        ['🈲', 'u7981', ['kanji', 'japanese', 'chinese', 'forbidden', 'limit', 'restricted', 'red-square']],
        ['🅰️', 'a', ['red-square', 'alphabet', 'letter']],
        ['🅱️', 'b', ['red-square', 'alphabet', 'letter']],
        ['🆎', 'ab', ['red-square', 'alphabet']],
        ['🆑', 'cl', ['alphabet', 'words', 'red-square']],
        ['🅾️', 'o2', ['alphabet', 'red-square', 'letter']],
        ['⛔', 'no entry', ['limit', 'security', 'privacy', 'bad', 'denied', 'stop', 'circle']],
        ['📛', 'name badge', ['fire', 'forbid']],
        ['🚫', 'no entry sign', ['forbid', 'stop', 'limit', 'denied', 'disallow', 'circle']],
        ['❌', 'x', ['no', 'delete', 'remove', 'cancel', 'red']],
        ['⭕', 'o', ['circle', 'round']],
        ['🛑', 'stop sign', ['stop']],
        ['💢', 'anger', ['angry', 'mad']],
        ['♨️', 'hotsprings', ['bath', 'warm', 'relax']],
        ['🚷', 'no pedestrians', ['rules', 'crossing', 'walking', 'circle']],
        ['🚯', 'do not litter', ['trash', 'bin', 'garbage', 'circle']],
        ['🚳', 'no bicycles', ['cyclist', 'prohibited', 'circle']],
        ['🚱', 'non-potable water', ['drink', 'faucet', 'tap', 'circle']],
        ['🔞', 'underage', ['18', 'drink', 'pub', 'night', 'minor', 'circle']],
        ['📵', 'no mobile phones', ['iphone', 'mute', 'circle']],
        ['❗', 'exclamation', ['heavy exclamation mark', 'danger', 'surprise', 'punctuation', 'wow', 'warning']],
        ['❕', 'grey exclamation', ['surprise', 'punctuation', 'gray', 'wow', 'warning']],
        ['❓', 'question', ['doubt', 'confused']],
        ['❔', 'grey question', ['doubts', 'gray', 'huh', 'confused']],
        ['‼️', 'bangbang', ['exclamation', 'surprise']],
        ['⁉️', 'interrobang', ['wat', 'punctuation', 'surprise']],
        ['💯', '100', ['score', 'perfect', 'numbers', 'century', 'exam', 'quiz', 'test', 'pass', 'hundred']],
        ['🔅', 'low brightness', ['sun', 'afternoon', 'warm', 'summer']],
        ['🔆', 'high brightness', ['sun', 'light']],
    ]) },
    { id: 'people', label: 'People & Body', icon: '👋', emoji: entries([
        ['🤲', 'palms up', ['hands', 'gesture', 'cupped', 'prayer']],
        ['👐', 'open hands', ['fingers', 'butterfly', 'hands', 'open']],
        ['🙌', 'raised hands', ['gesture', 'hooray', 'yea', 'celebration', 'hands']],
        ['👏', 'clap', ['hands', 'praise', 'applause', 'congrats', 'yay']],
        ['🤝', 'handshake', ['agreement', 'shake']],
        ['👍', '+1', ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like']],
        ['👎', '-1', ['thumbsdown', 'no', 'dislike', 'hand']],
        ['👊', 'facepunch', ['angry', 'violence', 'fist', 'hit', 'attack', 'hand']],
        ['✊', 'fist', ['fingers', 'hand', 'grasp']],
        ['🤛', 'fist left', ['hand', 'fistbump']],
        ['🤜', 'fist right', ['hand', 'fistbump']],
        ['🤞', 'crossed fingers', ['good', 'lucky']],
        ['✌', 'v', ['fingers', 'ohyeah', 'hand', 'peace', 'victory', 'two']],
        ['🤟', 'love you', ['hand', 'fingers', 'gesture']],
        ['🤘', 'metal', ['hand', 'fingers', 'evil eye', 'sign of horns', 'rock on']],
        ['👌', 'ok hand', ['fingers', 'limbs', 'perfect', 'ok', 'okay']],
        ['👈', 'point left', ['direction', 'fingers', 'hand', 'left']],
        ['👉', 'point right', ['fingers', 'hand', 'direction', 'right']],
        ['☝', 'point up', ['hand', 'fingers', 'direction', 'up']],
        ['👇', 'point down', ['fingers', 'hand', 'direction', 'down']],
        ['👆', 'point up 2', ['fingers', 'hand', 'direction', 'up']],
        ['✋', 'raised hand', ['fingers', 'stop', 'highfive', 'palm', 'ban']],
        ['🤚', 'raised back of hand', ['fingers', 'raised', 'backhand']],
        ['🖐', 'raised hand with fingers splayed', ['hand', 'fingers', 'palm']],
        ['🖖', 'vulcan salute', ['hand', 'fingers', 'spock', 'star trek']],
        ['👋', 'wave', ['hands', 'gesture', 'goodbye', 'solong', 'farewell', 'hello', 'hi', 'palm']],
        ['🤙', 'call me hand', ['hands', 'gesture']],
        ['💪', 'muscle', ['arm', 'flex', 'hand', 'summer', 'strong', 'biceps']],
        ['✍', 'writing hand', ['lower left ballpoint pen', 'stationery', 'write', 'compose']],
        ['🙏', 'pray', ['please', 'hope', 'wish', 'namaste', 'highfive']],
        ['🦶', 'foot', ['kick', 'stomp']],
        ['🦵', 'leg', ['kick', 'limb']],
        ['💍', 'ring', ['wedding', 'propose', 'marriage', 'valentines', 'diamond', 'fashion', 'jewelry', 'gem', 'engagement']],
        ['💄', 'lipstick', ['female', 'girl', 'fashion', 'woman']],
        ['💋', 'kiss', ['face', 'lips', 'love', 'like', 'affection', 'valentines']],
        ['👄', 'lips', ['mouth', 'kiss']],
        ['🦷', 'tooth', ['teeth', 'dentist']],
        ['👅', 'tongue', ['mouth', 'playful']],
        ['👂', 'ear', ['face', 'hear', 'sound', 'listen']],
        ['👃', 'nose', ['smell', 'sniff']],
        ['👣', 'footprints', ['feet', 'tracking', 'walking', 'beach']],
        ['👁', 'eye', ['face', 'look', 'see', 'watch', 'stare']],
        ['👀', 'eyes', ['look', 'watch', 'stalk', 'peek', 'see']],
        ['🧠', 'brain', ['smart', 'intelligent']],
        ['🗣', 'speaking head', ['user', 'person', 'human', 'sing', 'say', 'talk']],
        ['👤', 'bust in silhouette', ['user', 'person', 'human']],
        ['👥', 'busts in silhouette', ['user', 'person', 'human', 'group', 'team']],
        ['👶', 'baby', ['child', 'boy', 'girl', 'toddler']],
        ['👧', 'girl', ['female', 'woman', 'teenager']],
        ['🧒', 'child', ['gender-neutral', 'young']],
        ['👦', 'boy', ['man', 'male', 'guy', 'teenager']],
        ['🧑', 'adult', ['gender-neutral', 'person']],
        ['🧔', 'bearded person', ['person', 'bewhiskered']],
        ['🧓', 'older adult', ['human', 'elder', 'senior', 'gender-neutral']],
        ['👮‍♀️', 'policewoman', ['woman', 'police', 'law', 'legal', 'enforcement', 'arrest', '911', 'female']],
        ['👮', 'policeman', ['man', 'police', 'law', 'legal', 'enforcement', 'arrest', '911']],
        ['💂‍♀️', 'guardswoman', ['uk', 'gb', 'british', 'female', 'royal', 'woman']],
        ['💂', 'guardsman', ['uk', 'gb', 'british', 'male', 'guy', 'royal']],
        ['🕵️‍♀️', 'female detective', ['human', 'spy', 'detective', 'female', 'woman']],
        ['🕵', 'male detective', ['human', 'spy', 'detective']],
        ['👰', 'bride with veil', ['couple', 'marriage', 'wedding', 'woman', 'bride']],
        ['👸', 'princess', ['girl', 'woman', 'female', 'blond', 'crown', 'royal', 'queen']],
        ['🤴', 'prince', ['boy', 'man', 'male', 'crown', 'royal', 'king']],
        ['🤶', 'mrs claus', ['woman', 'female', 'xmas', 'mother christmas']],
        ['🎅', 'santa', ['festival', 'man', 'male', 'xmas', 'father christmas']],
        ['🧙‍♀️', 'sorceress', ['woman', 'female', 'mage', 'witch']],
        ['🧙‍♂️', 'wizard', ['man', 'male', 'mage', 'sorcerer']],
        ['🧜‍♀️', 'mermaid', ['woman', 'female', 'merwoman', 'ariel']],
        ['🧜‍♂️', 'merman', ['man', 'male', 'triton']],
        ['👼', 'angel', ['heaven', 'wings', 'halo']],
        ['🤱', 'breastfeeding', ['nursing', 'baby']],
        ['💅', 'nail care', ['beauty', 'manicure', 'finger', 'fashion', 'nail']],
        ['🤳', 'selfie', ['camera', 'phone']],
        ['💃', 'dancer', ['female', 'girl', 'woman', 'fun']],
        ['👯', 'dancing women', ['female', 'bunny', 'women', 'girls']],
        ['👯‍♂️', 'dancing men', ['male', 'bunny', 'men', 'boys']],
        ['👫', 'couple', ['pair', 'people', 'human', 'love', 'date', 'dating', 'like', 'affection', 'valentines', 'marriage']],
        ['👭', 'two women holding hands', ['pair', 'friendship', 'couple', 'love', 'like', 'female', 'people', 'human']],
        ['👬', 'two men holding hands', ['pair', 'couple', 'love', 'like', 'bromance', 'friendship', 'people', 'human']],
        ['🧶', 'yarn', ['ball', 'crochet', 'knit']],
        ['🧵', 'thread', ['needle', 'sewing', 'spool', 'string']],
        ['🧥', 'coat', ['jacket']],
        ['🥼', 'labcoat', ['doctor', 'experiment', 'scientist', 'chemist']],
        ['👚', 'womans clothes', ['fashion', 'shopping bags', 'female']],
        ['👕', 'tshirt', ['fashion', 'cloth', 'casual', 'shirt', 'tee']],
        ['👖', 'jeans', ['fashion', 'shopping']],
        ['👔', 'necktie', ['shirt', 'suitup', 'formal', 'fashion', 'cloth', 'business']],
        ['👗', 'dress', ['clothes', 'fashion', 'shopping']],
        ['👙', 'bikini', ['swimming', 'female', 'woman', 'girl', 'fashion', 'beach', 'summer']],
        ['👘', 'kimono', ['dress', 'fashion', 'women', 'female', 'japanese']],
        ['🥿', 'flat shoe', ['ballet', 'slip-on', 'slipper']],
        ['👠', 'high heel', ['fashion', 'shoes', 'female', 'pumps', 'stiletto']],
        ['👡', 'sandal', ['shoes', 'fashion', 'flip flops']],
        ['👢', 'boot', ['shoes', 'fashion']],
        ['👞', 'mans shoe', ['fashion', 'male']],
        ['👟', 'athletic shoe', ['shoes', 'sports', 'sneakers']],
        ['🥾', 'hiking boot', ['backpacking', 'camping', 'hiking']],
        ['🧦', 'socks', ['stockings', 'clothes']],
        ['🧤', 'gloves', ['hands', 'winter', 'clothes']],
        ['🧣', 'scarf', ['neck', 'winter', 'clothes']],
        ['🎩', 'tophat', ['magic', 'gentleman', 'classy', 'circus']],
        ['🧢', 'billed hat', ['cap', 'baseball']],
        ['👒', 'womans hat', ['fashion', 'accessories', 'female', 'lady', 'spring']],
        ['🎓', 'mortar board', ['school', 'college', 'degree', 'university', 'graduation', 'cap', 'hat', 'legal', 'learn', 'education']],
        ['⛑', 'rescue worker helmet', ['construction', 'build']],
        ['👑', 'crown', ['king', 'kod', 'leader', 'royalty', 'lord']],
        ['👝', 'pouch', ['bag', 'accessories', 'shopping']],
        ['👛', 'purse', ['fashion', 'accessories', 'money', 'sales', 'shopping']],
        ['👜', 'handbag', ['fashion', 'accessory', 'accessories', 'shopping']],
        ['💼', 'briefcase', ['business', 'documents', 'work', 'law', 'legal', 'job', 'career']],
        ['🎒', 'school satchel', ['student', 'education', 'bag', 'backpack']],
        ['🧳', 'luggage', ['packing', 'travel']],
        ['👓', 'eyeglasses', ['fashion', 'accessories', 'eyesight', 'nerdy', 'dork', 'geek']],
        ['🕶', 'dark sunglasses', ['face', 'cool', 'accessories']],
        ['🥽', 'goggles', ['eyes', 'protection', 'safety']],
        ['🌂', 'closed umbrella', ['weather', 'rain', 'drizzle']],
        ['💤', 'zzz', ['sleepy', 'tired', 'dream']],
    ]) },
    { id: 'nature', label: 'Animals & Nature', icon: '🌲', emoji: entries([
        ['🎃', 'jack o lantern', ['halloween', 'light', 'pumpkin', 'creepy', 'fall']],
        ['🐶', 'dog', ['animal', 'friend', 'nature', 'woof', 'puppy', 'pet', 'faithful']],
        ['🐱', 'cat', ['animal', 'meow', 'nature', 'pet', 'kitten']],
        ['🐭', 'mouse', ['animal', 'nature', 'cheese wedge', 'rodent']],
        ['🐹', 'hamster', ['animal', 'nature']],
        ['🐰', 'rabbit', ['animal', 'nature', 'pet', 'spring', 'magic', 'bunny']],
        ['🦊', 'fox face', ['animal', 'nature', 'face']],
        ['🐻', 'bear', ['animal', 'nature', 'wild']],
        ['🐼', 'panda face', ['animal', 'nature', 'panda']],
        ['🐨', 'koala', ['animal', 'nature']],
        ['🐯', 'tiger', ['animal', 'cat', 'danger', 'wild', 'nature', 'roar']],
        ['🦁', 'lion', ['animal', 'nature']],
        ['🐮', 'cow', ['beef', 'ox', 'animal', 'nature', 'moo', 'milk']],
        ['🐷', 'pig', ['animal', 'oink', 'nature']],
        ['🐽', 'pig nose', ['animal', 'oink']],
        ['🐸', 'frog', ['animal', 'nature', 'croak', 'toad']],
        ['🐵', 'monkey face', ['animal', 'nature', 'circus']],
        ['🙈', 'see no evil', ['monkey', 'animal', 'nature', 'haha']],
        ['🙉', 'hear no evil', ['animal', 'monkey', 'nature']],
        ['🙊', 'speak no evil', ['monkey', 'animal', 'nature', 'omg']],
        ['🐒', 'monkey', ['animal', 'nature', 'banana', 'circus']],
        ['🐔', 'chicken', ['animal', 'cluck', 'nature', 'bird']],
        ['🐧', 'penguin', ['animal', 'nature']],
        ['🐦', 'bird', ['animal', 'nature', 'fly', 'tweet', 'spring']],
        ['🐤', 'baby chick', ['animal', 'chicken', 'bird']],
        ['🐣', 'hatching chick', ['animal', 'chicken', 'egg', 'born', 'baby', 'bird']],
        ['🐥', 'hatched chick', ['animal', 'chicken', 'baby', 'bird']],
        ['🦆', 'duck', ['animal', 'nature', 'bird', 'mallard']],
        ['🦅', 'eagle', ['animal', 'nature', 'bird']],
        ['🦉', 'owl', ['animal', 'nature', 'bird', 'hoot']],
        ['🦇', 'bat', ['animal', 'nature', 'blind', 'vampire']],
        ['🐺', 'wolf', ['animal', 'nature', 'wild']],
        ['🐗', 'boar', ['animal', 'nature']],
        ['🐴', 'horse', ['animal', 'brown', 'nature']],
        ['🦄', 'unicorn', ['animal', 'nature', 'mystical']],
        ['🐝', 'honeybee', ['animal', 'insect', 'nature', 'bug', 'spring', 'honey']],
        ['🐛', 'bug', ['animal', 'insect', 'nature', 'worm']],
        ['🦋', 'butterfly', ['animal', 'insect', 'nature', 'caterpillar']],
        ['🐌', 'snail', ['slow', 'animal', 'shell']],
        ['🐚', 'shell', ['nature', 'sea', 'beach']],
        ['🐞', 'beetle', ['animal', 'insect', 'nature', 'ladybug']],
        ['🐜', 'ant', ['animal', 'insect', 'nature', 'bug']],
        ['🦟', 'mosquito', ['animal', 'nature', 'insect', 'malaria']],
        ['🦗', 'grasshopper', ['animal', 'cricket', 'chirp']],
        ['🕷', 'spider', ['animal', 'arachnid']],
        ['🕸', 'spider web', ['animal', 'insect', 'arachnid', 'silk']],
        ['🦂', 'scorpion', ['animal', 'arachnid']],
        ['🐢', 'turtle', ['animal', 'slow', 'nature', 'tortoise']],
        ['🐍', 'snake', ['animal', 'evil', 'nature', 'hiss', 'python']],
        ['🦎', 'lizard', ['animal', 'nature', 'reptile']],
        ['🦖', 't-rex', ['animal', 'nature', 'dinosaur', 'tyrannosaurus', 'extinct']],
        ['🦕', 'sauropod', ['animal', 'nature', 'dinosaur', 'brachiosaurus', 'brontosaurus', 'diplodocus', 'extinct']],
        ['🐙', 'octopus', ['animal', 'creature', 'ocean', 'sea', 'nature', 'beach']],
        ['🦑', 'squid', ['animal', 'nature', 'ocean', 'sea']],
        ['🦐', 'shrimp', ['animal', 'ocean', 'nature', 'seafood']],
        ['🦞', 'lobster', ['animal', 'nature', 'bisque', 'claws', 'seafood']],
        ['🦀', 'crab', ['animal', 'crustacean']],
        ['🐡', 'blowfish', ['animal', 'nature', 'food', 'sea', 'ocean']],
        ['🐠', 'tropical fish', ['animal', 'swim', 'ocean', 'beach', 'nemo']],
        ['🐟', 'fish', ['animal', 'food', 'nature']],
        ['🐬', 'dolphin', ['animal', 'nature', 'fish', 'sea', 'ocean', 'flipper', 'fins', 'beach']],
        ['🐳', 'whale', ['animal', 'nature', 'sea', 'ocean']],
        ['🐋', 'whale2', ['animal', 'nature', 'sea', 'ocean']],
        ['🦈', 'shark', ['animal', 'nature', 'fish', 'sea', 'ocean', 'jaws', 'fins', 'beach']],
        ['🐊', 'crocodile', ['animal', 'nature', 'reptile', 'lizard', 'alligator']],
        ['🐅', 'tiger2', ['animal', 'nature', 'roar']],
        ['🐆', 'leopard', ['animal', 'nature']],
        ['🦓', 'zebra', ['animal', 'nature', 'stripes', 'safari']],
        ['🦍', 'gorilla', ['animal', 'nature', 'circus']],
        ['🐘', 'elephant', ['animal', 'nature', 'nose', 'th', 'circus']],
        ['🦛', 'hippopotamus', ['animal', 'nature']],
        ['🦏', 'rhinoceros', ['animal', 'nature', 'horn']],
        ['🐪', 'dromedary camel', ['animal', 'hot', 'desert', 'hump']],
        ['🦒', 'giraffe', ['animal', 'nature', 'spots', 'safari']],
        ['🦘', 'kangaroo', ['animal', 'nature', 'australia', 'joey', 'hop', 'marsupial']],
        ['🐫', 'camel', ['animal', 'nature', 'hot', 'desert', 'hump']],
        ['🐃', 'water buffalo', ['animal', 'nature', 'ox', 'cow']],
        ['🐂', 'ox', ['animal', 'cow', 'beef']],
        ['🐄', 'cow2', ['beef', 'ox', 'animal', 'nature', 'moo', 'milk']],
        ['🐎', 'racehorse', ['animal', 'gamble', 'luck']],
        ['🐖', 'pig2', ['animal', 'nature']],
        ['🐏', 'ram', ['animal', 'sheep', 'nature']],
        ['🐑', 'sheep', ['animal', 'nature', 'wool', 'shipit']],
        ['🦙', 'llama', ['animal', 'nature', 'alpaca']],
        ['🐐', 'goat', ['animal', 'nature']],
        ['🦌', 'deer', ['animal', 'nature', 'horns', 'venison']],
        ['🐕', 'dog2', ['animal', 'nature', 'friend', 'doge', 'pet', 'faithful']],
        ['🐩', 'poodle', ['dog', 'animal', '101', 'nature', 'pet']],
        ['🐈', 'cat2', ['animal', 'meow', 'pet', 'cats']],
        ['🐓', 'rooster', ['animal', 'nature', 'chicken']],
        ['🦃', 'turkey', ['animal', 'bird']],
        ['🦚', 'peacock', ['animal', 'nature', 'peahen', 'bird']],
        ['🦜', 'parrot', ['animal', 'nature', 'bird', 'pirate', 'talk']],
        ['🦢', 'swan', ['animal', 'nature', 'bird']],
        ['🕊', 'dove', ['animal', 'bird']],
        ['🐇', 'rabbit2', ['animal', 'nature', 'pet', 'magic', 'spring']],
        ['🦝', 'raccoon', ['animal', 'nature']],
        ['🦡', 'badger', ['animal', 'nature', 'honey']],
        ['🐀', 'rat', ['animal', 'mouse', 'rodent']],
        ['🐁', 'mouse2', ['animal', 'nature', 'rodent']],
        ['🐿', 'chipmunk', ['animal', 'nature', 'rodent', 'squirrel']],
        ['🦔', 'hedgehog', ['animal', 'nature', 'spiny']],
        ['🐾', 'paw prints', ['animal', 'tracking', 'footprints', 'dog', 'cat', 'pet', 'feet']],
        ['🐉', 'dragon', ['animal', 'myth', 'nature', 'chinese', 'green']],
        ['🐲', 'dragon face', ['animal', 'myth', 'nature', 'chinese', 'green']],
        ['🌵', 'cactus', ['vegetable', 'plant', 'nature']],
        ['🎄', 'christmas tree', ['festival', 'vacation', 'december', 'xmas', 'celebration']],
        ['🌲', 'evergreen tree', ['plant', 'nature']],
        ['🌳', 'deciduous tree', ['plant', 'nature']],
        ['🌴', 'palm tree', ['plant', 'vegetable', 'nature', 'summer', 'beach', 'mojito', 'tropical']],
        ['🌱', 'seedling', ['plant', 'nature', 'grass', 'lawn', 'spring']],
        ['🌿', 'herb', ['vegetable', 'plant', 'medicine', 'weed', 'grass', 'lawn']],
        ['☘', 'shamrock', ['vegetable', 'plant', 'nature', 'irish', 'clover']],
        ['🍀', 'four leaf clover', ['vegetable', 'plant', 'nature', 'lucky', 'irish']],
        ['🎍', 'bamboo', ['plant', 'nature', 'vegetable', 'panda', 'pine decoration']],
        ['🎋', 'tanabata tree', ['plant', 'nature', 'branch', 'summer']],
        ['🍃', 'leaves', ['nature', 'plant', 'tree', 'vegetable', 'grass', 'lawn', 'spring']],
        ['🍂', 'fallen leaf', ['nature', 'plant', 'vegetable', 'leaves']],
        ['🍁', 'maple leaf', ['nature', 'plant', 'vegetable', 'ca', 'fall']],
        ['🌾', 'ear of rice', ['nature', 'plant']],
        ['🌺', 'hibiscus', ['plant', 'vegetable', 'flowers', 'beach']],
        ['🌻', 'sunflower', ['nature', 'plant', 'fall']],
        ['🌹', 'rose', ['flowers', 'valentines', 'love', 'spring']],
        ['🥀', 'wilted flower', ['plant', 'nature', 'flower']],
        ['🌷', 'tulip', ['flowers', 'plant', 'nature', 'summer', 'spring']],
        ['🌼', 'blossom', ['nature', 'flowers', 'yellow']],
        ['🌸', 'cherry blossom', ['nature', 'plant', 'spring', 'flower']],
        ['💐', 'bouquet', ['flowers', 'nature', 'spring']],
        ['🍄', 'mushroom', ['plant', 'vegetable']],
        ['🌎', 'earth americas', ['globe', 'world', 'usa', 'international']],
        ['🌍', 'earth africa', ['globe', 'world', 'international']],
        ['🌏', 'earth asia', ['globe', 'world', 'east', 'international']],
        ['🌕', 'full moon', ['nature', 'yellow', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌖', 'waning gibbous moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep', 'waxing gibbous moon']],
        ['🌗', 'last quarter moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌘', 'waning crescent moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌑', 'new moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌒', 'waxing crescent moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌓', 'first quarter moon', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌔', 'waxing gibbous moon', ['nature', 'night', 'sky', 'gray', 'twilight', 'planet', 'space', 'evening', 'sleep']],
        ['🌚', 'new moon with face', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌝', 'full moon with face', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌛', 'first quarter moon with face', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌜', 'last quarter moon with face', ['nature', 'twilight', 'planet', 'space', 'night', 'evening', 'sleep']],
        ['🌞', 'sun with face', ['nature', 'morning', 'sky']],
        ['🌙', 'crescent moon', ['night', 'sleep', 'sky', 'evening', 'magic']],
        ['⭐', 'star', ['night', 'yellow']],
        ['🌟', 'star2', ['night', 'sparkle', 'awesome', 'good', 'magic']],
        ['💫', 'dizzy', ['star', 'sparkle', 'shoot', 'magic']],
        ['✨', 'sparkles', ['stars', 'shine', 'shiny', 'cool', 'awesome', 'good', 'magic']],
        ['☄', 'comet', ['space']],
        ['☀️', 'sunny', ['weather', 'nature', 'brightness', 'summer', 'beach', 'spring']],
        ['🌤', 'sun behind small cloud', ['weather']],
        ['⛅', 'partly sunny', ['weather', 'nature', 'cloudy', 'morning', 'fall', 'spring']],
        ['🌥', 'sun behind large cloud', ['weather']],
        ['🌦', 'sun behind rain cloud', ['weather']],
        ['☁️', 'cloud', ['weather', 'sky']],
        ['🌧', 'cloud with rain', ['weather']],
        ['⛈', 'cloud with lightning and rain', ['weather', 'lightning']],
        ['🌩', 'cloud with lightning', ['weather', 'thunder']],
        ['🔥', 'fire', ['hot', 'cook', 'flame']],
        ['💥', 'boom', ['bomb', 'explode', 'explosion', 'collision', 'blown']],
        ['❄️', 'snowflake', ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas']],
        ['🌨', 'cloud with snow', ['weather']],
        ['⛄', 'snowman', ['winter', 'season', 'cold', 'weather', 'christmas', 'xmas', 'frozen', 'without snow']],
    ]) },
    { id: 'food', label: 'Food & Drink', icon: '☕', emoji: entries([
        ['🍏', 'green apple', ['fruit', 'nature']],
        ['🍎', 'apple', ['fruit', 'mac', 'school']],
        ['🍐', 'pear', ['fruit', 'nature', 'food']],
        ['🍊', 'tangerine', ['food', 'fruit', 'nature', 'orange']],
        ['🍋', 'lemon', ['fruit', 'nature']],
        ['🍌', 'banana', ['fruit', 'food', 'monkey']],
        ['🍉', 'watermelon', ['fruit', 'food', 'picnic', 'summer']],
        ['🍇', 'grapes', ['fruit', 'food', 'wine']],
        ['🍓', 'strawberry', ['fruit', 'food', 'nature']],
        ['🍈', 'melon', ['fruit', 'nature', 'food']],
        ['🍒', 'cherries', ['food', 'fruit']],
        ['🍑', 'peach', ['fruit', 'nature', 'food']],
        ['🥭', 'mango', ['fruit', 'food', 'tropical']],
        ['🍍', 'pineapple', ['fruit', 'nature', 'food']],
        ['🥥', 'coconut', ['fruit', 'nature', 'food', 'palm']],
        ['🥝', 'kiwi fruit', ['fruit', 'food']],
        ['🍅', 'tomato', ['fruit', 'vegetable', 'nature', 'food']],
        ['🍆', 'eggplant', ['vegetable', 'nature', 'food', 'aubergine']],
        ['🥑', 'avocado', ['fruit', 'food']],
        ['🥦', 'broccoli', ['fruit', 'food', 'vegetable']],
        ['🥬', 'leafy greens', ['food', 'vegetable', 'plant', 'bok choy', 'cabbage', 'kale', 'lettuce']],
        ['🥒', 'cucumber', ['fruit', 'food', 'pickle']],
        ['🌶', 'hot pepper', ['food', 'spicy', 'chilli', 'chili']],
        ['🌽', 'corn', ['food', 'vegetable', 'plant']],
        ['🥕', 'carrot', ['vegetable', 'food', 'orange']],
        ['🥔', 'potato', ['food', 'tuber', 'vegatable', 'starch']],
        ['🍠', 'sweet potato', ['food', 'nature']],
        ['🥐', 'croissant', ['food', 'bread', 'french']],
        ['🥯', 'bagel', ['food', 'bread', 'bakery', 'schmear']],
        ['🍞', 'bread', ['food', 'wheat', 'breakfast', 'toast']],
        ['🥖', 'baguette bread', ['food', 'bread', 'french']],
        ['🥨', 'pretzel', ['food', 'bread', 'twisted']],
        ['🧀', 'cheese', ['food', 'chadder']],
        ['🥚', 'egg', ['food', 'chicken', 'breakfast']],
        ['🍳', 'fried egg', ['food', 'breakfast', 'kitchen', 'egg']],
        ['🥞', 'pancakes', ['food', 'breakfast', 'flapjacks', 'hotcakes']],
        ['🥓', 'bacon', ['food', 'breakfast', 'pork', 'pig', 'meat']],
        ['🥩', 'steak', ['food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop']],
        ['🍗', 'poultry leg', ['food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey']],
        ['🍖', 'meat on bone', ['good', 'food', 'drumstick']],
        ['🦴', 'bone', ['skeleton']],
        ['🌭', 'hotdog', ['food', 'frankfurter']],
        ['🍔', 'hamburger', ['meat', 'fast food', 'beef', 'cheeseburger', 'mcdonalds', 'burger king']],
        ['🍟', 'fries', ['chips', 'snack', 'fast food']],
        ['🍕', 'pizza', ['food', 'party']],
        ['🥪', 'sandwich', ['food', 'lunch', 'bread']],
        ['🥙', 'stuffed flatbread', ['food', 'flatbread', 'stuffed', 'gyro']],
        ['🌮', 'taco', ['food', 'mexican']],
        ['🌯', 'burrito', ['food', 'mexican']],
        ['🥗', 'green salad', ['food', 'healthy', 'lettuce']],
        ['🥘', 'shallow pan of food', ['food', 'cooking', 'casserole', 'paella']],
        ['🥫', 'canned food', ['food', 'soup']],
        ['🍝', 'spaghetti', ['food', 'italian', 'noodle']],
        ['🍜', 'ramen', ['food', 'japanese', 'noodle', 'chopsticks']],
        ['🍲', 'stew', ['food', 'meat', 'soup']],
        ['🍛', 'curry', ['food', 'spicy', 'hot', 'indian']],
        ['🍣', 'sushi', ['food', 'fish', 'japanese', 'rice']],
        ['🍱', 'bento', ['food', 'japanese', 'box']],
        ['🍤', 'fried shrimp', ['food', 'animal', 'appetizer', 'summer']],
        ['🍙', 'rice ball', ['food', 'japanese']],
        ['🍚', 'rice', ['food', 'china', 'asian']],
        ['🍘', 'rice cracker', ['food', 'japanese']],
        ['🍥', 'fish cake', ['food', 'japan', 'sea', 'beach', 'narutomaki', 'pink', 'swirl', 'kamaboko', 'surimi', 'ramen']],
        ['🥠', 'fortune cookie', ['food', 'prophecy']],
        ['🥮', 'moon cake', ['food', 'autumn']],
        ['🍢', 'oden', ['food', 'japanese']],
        ['🍡', 'dango', ['food', 'dessert', 'sweet', 'japanese', 'barbecue', 'meat']],
        ['🍧', 'shaved ice', ['hot', 'dessert', 'summer']],
        ['🍨', 'ice cream', ['food', 'hot', 'dessert']],
        ['🍦', 'icecream', ['food', 'hot', 'dessert', 'summer']],
        ['🥧', 'pie', ['food', 'dessert', 'pastry']],
        ['🧁', 'cupcake', ['food', 'dessert', 'bakery', 'sweet']],
        ['🍰', 'cake', ['food', 'dessert']],
        ['🎂', 'birthday', ['food', 'dessert', 'cake']],
        ['🍮', 'custard', ['dessert', 'food']],
        ['🍭', 'lollipop', ['food', 'snack', 'candy', 'sweet']],
        ['🍬', 'candy', ['snack', 'dessert', 'sweet', 'lolly']],
        ['🍫', 'chocolate bar', ['food', 'snack', 'dessert', 'sweet']],
        ['🍿', 'popcorn', ['food', 'movie theater', 'films', 'snack']],
        ['🍩', 'doughnut', ['food', 'dessert', 'snack', 'sweet', 'donut']],
        ['🥟', 'dumpling', ['food', 'empanada', 'pierogi', 'potsticker']],
        ['🍪', 'cookie', ['food', 'snack', 'oreo', 'chocolate', 'sweet', 'dessert']],
        ['🥜', 'peanuts', ['food', 'nut']],
        ['🍯', 'honey pot', ['bees', 'sweet', 'kitchen']],
        ['🥛', 'milk glass', ['beverage', 'drink', 'cow']],
        ['🍼', 'baby bottle', ['food', 'container', 'milk']],
        ['☕', 'coffee', ['beverage', 'caffeine', 'latte', 'espresso']],
        ['🍵', 'tea', ['drink', 'bowl', 'breakfast', 'green', 'british']],
        ['🥤', 'cup with straw', ['drink', 'soda']],
        ['🍶', 'sake', ['wine', 'drink', 'drunk', 'beverage', 'japanese', 'alcohol', 'booze']],
        ['🍺', 'beer', ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze']],
        ['🍻', 'beers', ['relax', 'beverage', 'drink', 'drunk', 'party', 'pub', 'summer', 'alcohol', 'booze']],
        ['🥂', 'clinking glasses', ['beverage', 'drink', 'party', 'alcohol', 'celebrate', 'cheers', 'wine', 'champagne', 'toast']],
        ['🍷', 'wine glass', ['drink', 'beverage', 'drunk', 'alcohol', 'booze']],
        ['🥃', 'tumbler glass', ['drink', 'beverage', 'drunk', 'alcohol', 'liquor', 'booze', 'bourbon', 'scotch', 'whisky', 'glass', 'shot']],
        ['🍸', 'cocktail', ['drink', 'drunk', 'alcohol', 'beverage', 'booze', 'mojito']],
        ['🍹', 'tropical drink', ['beverage', 'cocktail', 'summer', 'beach', 'alcohol', 'booze', 'mojito']],
        ['🍾', 'champagne', ['drink', 'wine', 'bottle', 'celebration']],
        ['🥄', 'spoon', ['cutlery', 'kitchen', 'tableware']],
        ['🍴', 'fork and knife', ['cutlery', 'kitchen']],
        ['🍽', 'plate with cutlery', ['food', 'eat', 'meal', 'lunch', 'dinner', 'restaurant']],
        ['🥣', 'bowl with spoon', ['food', 'breakfast', 'cereal', 'oatmeal', 'porridge']],
        ['🥡', 'takeout box', ['food', 'leftovers']],
        ['🥢', 'chopsticks', ['food']],
        ['🧂', 'salt', ['condiment', 'shaker']],
    ]) },
    { id: 'activities', label: 'Activities', icon: '🎉', emoji: entries([
        ['👾', 'space invader', ['game', 'arcade', 'play']],
        ['🕴', 'business suit levitating', ['suit', 'business', 'levitate', 'hover', 'jump']],
        ['⚽', 'soccer', ['sports', 'football']],
        ['🏀', 'basketball', ['sports', 'balls', 'nba']],
        ['🏈', 'football', ['sports', 'balls', 'nfl']],
        ['⚾', 'baseball', ['sports', 'balls']],
        ['🥎', 'softball', ['sports', 'balls']],
        ['🎾', 'tennis', ['sports', 'balls', 'green']],
        ['🏐', 'volleyball', ['sports', 'balls']],
        ['🏉', 'rugby football', ['sports', 'team']],
        ['🥏', 'flying disc', ['sports', 'frisbee', 'ultimate']],
        ['🎱', '8ball', ['pool', 'hobby', 'game', 'luck', 'magic']],
        ['⛳', 'golf', ['sports', 'business', 'flag', 'hole', 'summer']],
        ['🏌️‍♀️', 'golfing woman', ['sports', 'business', 'woman', 'female']],
        ['🏌', 'golfing man', ['sports', 'business']],
        ['🏓', 'ping pong', ['sports', 'pingpong']],
        ['🏸', 'badminton', ['sports']],
        ['🥅', 'goal net', ['sports']],
        ['🏒', 'ice hockey', ['sports']],
        ['🏑', 'field hockey', ['sports']],
        ['🥍', 'lacrosse', ['sports', 'ball', 'stick']],
        ['🏏', 'cricket', ['sports']],
        ['🎿', 'ski', ['sports', 'winter', 'cold', 'snow']],
        ['⛷', 'skier', ['sports', 'winter', 'snow']],
        ['🏂', 'snowboarder', ['sports', 'winter']],
        ['🤺', 'person fencing', ['sports', 'fencing', 'sword']],
        ['🤼‍♀️', 'women wrestling', ['sports', 'wrestlers']],
        ['🤼‍♂️', 'men wrestling', ['sports', 'wrestlers']],
        ['🤸‍♀️', 'woman cartwheeling', ['gymnastics']],
        ['🤸‍♂️', 'man cartwheeling', ['gymnastics']],
        ['🤾‍♀️', 'woman playing handball', ['sports']],
        ['🤾‍♂️', 'man playing handball', ['sports']],
        ['⛸', 'ice skate', ['sports']],
        ['🥌', 'curling stone', ['sports']],
        ['🛹', 'skateboard', ['board']],
        ['🛷', 'sled', ['sleigh', 'luge', 'toboggan']],
        ['🏹', 'bow and arrow', ['sports']],
        ['🎣', 'fishing pole and fish', ['food', 'hobby', 'summer']],
        ['🥊', 'boxing glove', ['sports', 'fighting']],
        ['🥋', 'martial arts uniform', ['judo', 'karate', 'taekwondo']],
        ['🚣‍♀️', 'rowing woman', ['sports', 'hobby', 'water', 'ship', 'woman', 'female']],
        ['🚣', 'rowing man', ['sports', 'hobby', 'water', 'ship']],
        ['🧗‍♀️', 'climbing woman', ['sports', 'hobby', 'woman', 'female', 'rock']],
        ['🧗‍♂️', 'climbing man', ['sports', 'hobby', 'man', 'male', 'rock']],
        ['🏊‍♀️', 'swimming woman', ['sports', 'exercise', 'human', 'athlete', 'water', 'summer', 'woman', 'female']],
        ['🏊', 'swimming man', ['sports', 'exercise', 'human', 'athlete', 'water', 'summer']],
        ['🤽‍♀️', 'woman playing water polo', ['sports', 'pool']],
        ['🤽‍♂️', 'man playing water polo', ['sports', 'pool']],
        ['🧘‍♀️', 'woman in lotus position', ['woman', 'female', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness']],
        ['🧘‍♂️', 'man in lotus position', ['man', 'male', 'meditation', 'yoga', 'serenity', 'zen', 'mindfulness']],
        ['🏄‍♀️', 'surfing woman', ['sports', 'ocean', 'sea', 'summer', 'beach', 'woman', 'female']],
        ['🏄', 'surfing man', ['sports', 'ocean', 'sea', 'summer', 'beach']],
        ['⛹️‍♀️', 'basketball woman', ['sports', 'human', 'woman', 'female']],
        ['⛹', 'basketball man', ['sports', 'human']],
        ['🏋️‍♀️', 'weight lifting woman', ['sports', 'training', 'exercise', 'woman', 'female']],
        ['🏋', 'weight lifting man', ['sports', 'training', 'exercise']],
        ['🚴‍♀️', 'biking woman', ['sports', 'bike', 'exercise', 'hipster', 'woman', 'female']],
        ['🚴', 'biking man', ['sports', 'bike', 'exercise', 'hipster']],
        ['🚵‍♀️', 'mountain biking woman', ['transportation', 'sports', 'human', 'race', 'bike', 'woman', 'female']],
        ['🚵', 'mountain biking man', ['transportation', 'sports', 'human', 'race', 'bike']],
        ['🏇', 'horse racing', ['animal', 'betting', 'competition', 'gambling', 'luck']],
        ['🏆', 'trophy', ['win', 'award', 'contest', 'place', 'ftw', 'ceremony']],
        ['🎽', 'running shirt with sash', ['play', 'pageant']],
        ['🏅', 'medal sports', ['award', 'winning']],
        ['🎖', 'medal military', ['award', 'winning', 'army']],
        ['🥇', '1st place medal', ['award', 'winning', 'first']],
        ['🥈', '2nd place medal', ['award', 'second']],
        ['🥉', '3rd place medal', ['award', 'third']],
        ['🎗', 'reminder ribbon', ['sports', 'cause', 'support', 'awareness']],
        ['🏵', 'rosette', ['flower', 'decoration', 'military']],
        ['🎫', 'ticket', ['event', 'concert', 'pass']],
        ['🎟', 'tickets', ['sports', 'concert', 'entrance']],
        ['🎭', 'performing arts', ['acting', 'theater', 'drama']],
        ['🎨', 'art', ['design', 'paint', 'draw', 'colors']],
        ['🎪', 'circus tent', ['festival', 'carnival', 'party']],
        ['🤹‍♀️', 'woman juggling', ['juggle', 'balance', 'skill', 'multitask']],
        ['🤹‍♂️', 'man juggling', ['juggle', 'balance', 'skill', 'multitask']],
        ['🎤', 'microphone', ['sound', 'music', 'pa', 'sing', 'talkshow']],
        ['🎼', 'musical score', ['treble', 'clef', 'compose']],
        ['🎹', 'musical keyboard', ['piano', 'instrument', 'compose']],
        ['🥁', 'drum', ['music', 'instrument', 'drumsticks', 'snare']],
        ['🎷', 'saxophone', ['music', 'instrument', 'jazz', 'blues']],
        ['🎺', 'trumpet', ['music', 'brass']],
        ['🎸', 'guitar', ['music', 'instrument']],
        ['🎻', 'violin', ['music', 'instrument', 'orchestra', 'symphony']],
        ['🎬', 'clapper', ['movie', 'film', 'record']],
        ['🎮', 'video game', ['play', 'console', 'ps4', 'controller']],
        ['🎯', 'dart', ['game', 'play', 'bar', 'target', 'bullseye']],
        ['🎲', 'game die', ['dice', 'random', 'tabletop', 'play', 'luck']],
        ['♟', 'chess pawn', ['expendable']],
        ['🎰', 'slot machine', ['bet', 'gamble', 'vegas', 'fruit machine', 'luck', 'casino']],
        ['🧩', 'jigsaw', ['interlocking', 'puzzle', 'piece']],
        ['🎳', 'bowling', ['sports', 'fun', 'play']],
        ['🛀', 'bath', ['clean', 'shower', 'bathroom']],
    ]) },
    { id: 'travel', label: 'Travel & Places', icon: '🚗', emoji: entries([
        ['🗼', 'tower', ['radio', 'communications', 'broadcast']],
        ['🛰️', 'satellite', ['space', 'communications', 'radio']],
        ['🚗', 'red car', ['red', 'transportation', 'vehicle']],
        ['🚕', 'taxi', ['uber', 'vehicle', 'cars', 'transportation']],
        ['🚙', 'blue car', ['transportation', 'vehicle']],
        ['🚌', 'bus', ['car', 'vehicle', 'transportation']],
        ['🚎', 'trolleybus', ['bart', 'transportation', 'vehicle']],
        ['🏎', 'racing car', ['sports', 'race', 'fast', 'formula', 'f1']],
        ['🚓', 'police car', ['vehicle', 'cars', 'transportation', 'law', 'legal', 'enforcement']],
        ['🚑', 'ambulance', ['health', '911', 'hospital']],
        ['🚒', 'fire engine', ['transportation', 'cars', 'vehicle']],
        ['🚐', 'minibus', ['vehicle', 'car', 'transportation']],
        ['🚚', 'truck', ['cars', 'transportation']],
        ['🚛', 'articulated lorry', ['vehicle', 'cars', 'transportation', 'express']],
        ['🚜', 'tractor', ['vehicle', 'car', 'farming', 'agriculture']],
        ['🛴', 'kick scooter', ['vehicle', 'kick', 'razor']],
        ['🏍', 'motorcycle', ['race', 'sports', 'fast']],
        ['🚲', 'bike', ['sports', 'bicycle', 'exercise', 'hipster']],
        ['🛵', 'motor scooter', ['vehicle', 'vespa', 'sasha']],
        ['🚨', 'rotating light', ['police', 'ambulance', '911', 'emergency', 'alert', 'error', 'pinged', 'law', 'legal']],
        ['🚔', 'oncoming police car', ['vehicle', 'law', 'legal', 'enforcement', '911']],
        ['🚍', 'oncoming bus', ['vehicle', 'transportation']],
        ['🚘', 'oncoming automobile', ['car', 'vehicle', 'transportation']],
        ['🚖', 'oncoming taxi', ['vehicle', 'cars', 'uber']],
        ['🚡', 'aerial tramway', ['transportation', 'vehicle', 'ski']],
        ['🚠', 'mountain cableway', ['transportation', 'vehicle', 'ski']],
        ['🚟', 'suspension railway', ['vehicle', 'transportation']],
        ['🚃', 'railway car', ['transportation', 'vehicle']],
        ['🚋', 'train', ['transportation', 'vehicle', 'carriage', 'public', 'travel']],
        ['🚝', 'monorail', ['transportation', 'vehicle']],
        ['🚄', 'bullettrain side', ['transportation', 'vehicle']],
        ['🚅', 'bullettrain front', ['transportation', 'vehicle', 'speed', 'fast', 'public', 'travel']],
        ['🚈', 'light rail', ['transportation', 'vehicle']],
        ['🚞', 'mountain railway', ['transportation', 'vehicle']],
        ['🚂', 'steam locomotive', ['transportation', 'vehicle', 'train']],
        ['🚆', 'train2', ['transportation', 'vehicle']],
        ['🚇', 'metro', ['transportation', 'blue-square', 'mrt', 'underground', 'tube']],
        ['🚊', 'tram', ['transportation', 'vehicle']],
        ['🚉', 'station', ['transportation', 'vehicle', 'public']],
        ['🛸', 'flying saucer', ['transportation', 'vehicle', 'ufo']],
        ['🚁', 'helicopter', ['transportation', 'vehicle', 'fly']],
        ['🛩', 'small airplane', ['flight', 'transportation', 'fly', 'vehicle']],
        ['✈️', 'airplane', ['vehicle', 'transportation', 'flight', 'fly']],
        ['🛫', 'flight departure', ['airport', 'flight', 'landing']],
        ['🛬', 'flight arrival', ['airport', 'flight', 'boarding']],
        ['⛵', 'sailboat', ['ship', 'summer', 'transportation', 'water', 'sailing']],
        ['🛥', 'motor boat', ['ship']],
        ['🚤', 'speedboat', ['ship', 'transportation', 'vehicle', 'summer']],
        ['⛴', 'ferry', ['boat', 'ship', 'yacht']],
        ['🛳', 'passenger ship', ['yacht', 'cruise', 'ferry']],
        ['🚀', 'rocket', ['launch', 'ship', 'staffmode', 'nasa', 'outer space', 'fly']],
        ['🛰', 'artificial satellite', ['communication', 'gps', 'orbit', 'spaceflight', 'nasa', 'iss']],
        ['💺', 'seat', ['sit', 'airplane', 'transport', 'bus', 'flight', 'fly']],
        ['🛶', 'canoe', ['boat', 'paddle', 'water', 'ship']],
        ['⚓', 'anchor', ['ship', 'ferry', 'sea', 'boat']],
        ['🚧', 'construction', ['wip', 'progress', 'caution', 'warning']],
        ['⛽', 'fuelpump', ['gas station', 'petroleum']],
        ['🚏', 'busstop', ['transportation', 'wait']],
        ['🚦', 'vertical traffic light', ['transportation', 'driving']],
        ['🚥', 'traffic light', ['transportation', 'signal']],
        ['🚢', 'ship', ['transportation', 'titanic', 'deploy']],
        ['🎡', 'ferris wheel', ['photo', 'carnival', 'londoneye']],
        ['🎢', 'roller coaster', ['carnival', 'playground', 'photo', 'fun']],
        ['🎠', 'carousel horse', ['photo', 'carnival']],
        ['🏗', 'building construction', ['wip', 'working', 'progress']],
        ['🌁', 'foggy', ['photo', 'mountain']],
        ['🏭', 'factory', ['building', 'industry', 'pollution', 'smoke']],
        ['⛲', 'fountain', ['photo', 'summer', 'water', 'fresh']],
        ['🎑', 'rice scene', ['photo', 'japan', 'asia', 'tsukimi']],
        ['⛰', 'mountain', ['photo', 'nature', 'environment']],
        ['🏔', 'mountain snow', ['photo', 'nature', 'environment', 'winter', 'cold']],
        ['🗻', 'mount fuji', ['photo', 'mountain', 'nature', 'japanese']],
        ['🌋', 'volcano', ['photo', 'nature', 'disaster']],
        ['🗾', 'japan', ['nation', 'country', 'japanese', 'asia']],
        ['🏕', 'camping', ['photo', 'outdoors', 'tent']],
        ['⛺', 'tent', ['photo', 'camping', 'outdoors']],
        ['🏞', 'national park', ['photo', 'environment', 'nature']],
        ['🛣', 'motorway', ['road', 'cupertino', 'interstate', 'highway']],
        ['🛤', 'railway track', ['train', 'transportation']],
        ['🌅', 'sunrise', ['morning', 'view', 'vacation', 'photo']],
        ['🌄', 'sunrise over mountains', ['view', 'vacation', 'photo']],
        ['🏜', 'desert', ['photo', 'warm', 'saharah']],
        ['🏖', 'beach umbrella', ['weather', 'summer', 'sunny', 'sand', 'mojito']],
        ['🏝', 'desert island', ['photo', 'tropical', 'mojito']],
        ['🌇', 'city sunrise', ['photo', 'good morning', 'dawn']],
        ['🌆', 'city sunset', ['photo', 'evening', 'sky', 'buildings']],
        ['🏙', 'cityscape', ['photo', 'night life', 'urban']],
        ['🌃', 'night with stars', ['evening', 'city', 'downtown']],
        ['🌉', 'bridge at night', ['photo', 'sanfrancisco']],
        ['🌌', 'milky way', ['photo', 'space', 'stars']],
        ['🌠', 'stars', ['night', 'photo']],
        ['🎇', 'sparkler', ['stars', 'night', 'shine']],
        ['🎆', 'fireworks', ['photo', 'festival', 'carnival', 'congratulations']],
        ['🌈', 'rainbow', ['nature', 'happy', 'unicorn face', 'photo', 'sky', 'spring']],
        ['🏘', 'houses', ['buildings', 'photo']],
        ['🏰', 'european castle', ['building', 'royalty', 'history']],
        ['🏯', 'japanese castle', ['photo', 'building']],
        ['🏟', 'stadium', ['photo', 'place', 'sports', 'concert', 'venue']],
        ['🗽', 'statue of liberty', ['american', 'newyork']],
        ['🏠', 'house', ['building', 'home']],
        ['🏡', 'house with garden', ['home', 'plant', 'nature']],
        ['🏚', 'derelict house', ['abandon', 'evict', 'broken', 'building']],
        ['🏢', 'office', ['building', 'bureau', 'work']],
        ['🏬', 'department store', ['building', 'shopping', 'mall']],
        ['🏣', 'post office', ['building', 'envelope', 'communication']],
        ['🏤', 'european post office', ['building', 'email']],
        ['🏥', 'hospital', ['building', 'health', 'surgery', 'doctor']],
        ['🏦', 'bank', ['building', 'money', 'sales', 'cash', 'business', 'enterprise']],
        ['🏨', 'hotel', ['building', 'accomodation', 'checkin']],
        ['🏪', 'convenience store', ['building', 'shopping', 'groceries']],
        ['🏫', 'school', ['building', 'student', 'education', 'learn', 'teach']],
        ['🏩', 'love hotel', ['like', 'affection', 'dating']],
        ['💒', 'wedding', ['love', 'like', 'affection', 'couple', 'marriage', 'bride', 'groom']],
        ['🏛', 'classical building', ['art', 'culture', 'history']],
        ['⛪', 'church', ['building', 'religion', 'christ']],
    ]) },
    { id: 'objects', label: 'Objects', icon: '📻', emoji: entries([
        ['📻', 'radio', ['ham', 'amateur', 'communications', 'receiver']],
        ['🎙️', 'studio microphone', ['mic', 'broadcast', 'radio']],
        ['🎧', 'headphones', ['audio', 'listen', 'radio']],
        ['📡', 'satellite antenna', ['radio', 'signal', 'communications']],
        ['📞', 'telephone receiver', ['call', 'phone']],
        ['☎️', 'telephone', ['call', 'phone']],
        ['📱', 'mobile phone', ['cell', 'telephone']],
        ['🔊', 'speaker high volume', ['audio', 'sound', 'loud']],
        ['🔇', 'muted speaker', ['audio', 'sound', 'quiet']],
        ['🔔', 'bell', ['alert', 'notification']],
        ['🔋', 'battery', ['power', 'energy']],
        ['🔌', 'electric plug', ['power', 'energy']],
        ['💻', 'laptop computer', ['technology', 'pc']],
        ['🖥️', 'desktop computer', ['technology', 'monitor']],
        ['⌨️', 'keyboard', ['computer', 'typing']],
        ['🛜', 'wireless network', ['wifi', 'internet', 'signal']],
        ['☠', 'skull and crossbones', ['poison', 'danger', 'deadly', 'scary', 'death', 'pirate', 'evil']],
        ['⌚', 'watch', ['time', 'accessories']],
        ['📲', 'calling', ['iphone', 'incoming']],
        ['⌨', 'keyboard', ['technology', 'computer', 'type', 'input', 'text']],
        ['🖥', 'desktop computer', ['technology', 'computing', 'screen']],
        ['🖨', 'printer', ['paper', 'ink']],
        ['🖱', 'computer mouse', ['click']],
        ['🖲', 'trackball', ['technology', 'trackpad']],
        ['🕹', 'joystick', ['game', 'play']],
        ['🗜', 'clamp', ['tool']],
        ['💽', 'minidisc', ['technology', 'record', 'data', 'disk', '90s']],
        ['💾', 'floppy disk', ['oldschool', 'technology', 'save', '90s', '80s']],
        ['💿', 'cd', ['technology', 'dvd', 'disk', 'disc', '90s']],
        ['📀', 'dvd', ['cd', 'disk', 'disc']],
        ['📼', 'vhs', ['record', 'video', 'oldschool', '90s', '80s']],
        ['📷', 'camera', ['gadgets', 'photography']],
        ['📸', 'camera flash', ['photography', 'gadgets']],
        ['📹', 'video camera', ['film', 'record']],
        ['🎥', 'movie camera', ['film', 'record']],
        ['📽', 'film projector', ['video', 'tape', 'record', 'movie']],
        ['🎞', 'film strip', ['movie']],
        ['📟', 'pager', ['bbcall', 'oldschool', '90s']],
        ['📠', 'fax', ['communication', 'technology']],
        ['📺', 'tv', ['technology', 'program', 'oldschool', 'show', 'television']],
        ['🎙', 'studio microphone', ['sing', 'recording', 'artist', 'talkshow']],
        ['🎚', 'level slider', ['scale']],
        ['🎛', 'control knobs', ['dial']],
        ['🧭', 'compass', ['magnetic', 'navigation', 'orienteering']],
        ['⏱', 'stopwatch', ['time', 'deadline']],
        ['⏲', 'timer clock', ['alarm']],
        ['⏰', 'alarm clock', ['time', 'wake']],
        ['🕰', 'mantelpiece clock', ['time']],
        ['⏳', 'hourglass flowing sand', ['oldschool', 'time', 'countdown']],
        ['⌛', 'hourglass', ['time', 'clock', 'oldschool', 'limit', 'exam', 'quiz', 'test']],
        ['💡', 'bulb', ['light', 'electricity', 'idea']],
        ['🔦', 'flashlight', ['dark', 'camping', 'sight', 'night']],
        ['🕯', 'candle', ['fire', 'wax']],
        ['🧯', 'fire extinguisher', ['quench']],
        ['🗑', 'wastebasket', ['bin', 'trash', 'rubbish', 'garbage', 'toss']],
        ['🛢', 'oil drum', ['barrell']],
        ['💸', 'money with wings', ['dollar', 'bills', 'payment', 'sale']],
        ['💵', 'dollar', ['money', 'sales', 'bill', 'currency']],
        ['💴', 'yen', ['money', 'sales', 'japanese', 'dollar', 'currency']],
        ['💶', 'euro', ['money', 'sales', 'dollar', 'currency']],
        ['💷', 'pound', ['british', 'sterling', 'money', 'sales', 'bills', 'uk', 'england', 'currency']],
        ['💰', 'moneybag', ['dollar', 'payment', 'coins', 'sale']],
        ['💳', 'credit card', ['money', 'sales', 'dollar', 'bill', 'payment', 'shopping']],
        ['💎', 'gem', ['blue', 'ruby', 'diamond', 'jewelry']],
        ['⚖', 'balance scale', ['law', 'fairness', 'weight']],
        ['🧰', 'toolbox', ['tools', 'diy', 'fix', 'maintainer', 'mechanic']],
        ['🔧', 'wrench', ['tools', 'diy', 'ikea', 'fix', 'maintainer']],
        ['🔨', 'hammer', ['tools', 'build', 'create']],
        ['⚒', 'hammer and pick', ['tools', 'build', 'create']],
        ['🛠', 'hammer and wrench', ['tools', 'build', 'create']],
        ['⛏', 'pick', ['tools', 'dig']],
        ['🔩', 'nut and bolt', ['handy', 'tools', 'fix']],
        ['⚙', 'gear', ['cog']],
        ['🧱', 'brick', ['bricks']],
        ['⛓', 'chains', ['lock', 'arrest']],
        ['🧲', 'magnet', ['attraction', 'magnetic']],
        ['🔫', 'gun', ['violence', 'weapon', 'pistol', 'revolver']],
        ['💣', 'bomb', ['boom', 'explode', 'explosion', 'terrorism']],
        ['🧨', 'firecracker', ['dynamite', 'boom', 'explode', 'explosion', 'explosive']],
        ['🔪', 'hocho', ['knife', 'blade', 'cutlery', 'kitchen', 'weapon']],
        ['🗡', 'dagger', ['weapon']],
        ['⚔', 'crossed swords', ['weapon']],
        ['🛡', 'shield', ['protection', 'security']],
        ['🚬', 'smoking', ['kills', 'tobacco', 'cigarette', 'joint', 'smoke']],
        ['⚰', 'coffin', ['vampire', 'dead', 'die', 'death', 'rip', 'graveyard', 'cemetery', 'casket', 'funeral', 'box']],
        ['⚱', 'funeral urn', ['dead', 'die', 'death', 'rip', 'ashes']],
        ['🏺', 'amphora', ['vase', 'jar']],
        ['🔮', 'crystal ball', ['disco', 'party', 'magic', 'circus', 'fortune teller']],
        ['📿', 'prayer beads', ['dhikr', 'religious']],
        ['🧿', 'nazar amulet', ['bead', 'charm']],
        ['💈', 'barber', ['hair', 'salon', 'style']],
        ['⚗', 'alembic', ['distilling', 'science', 'experiment', 'chemistry']],
        ['🔭', 'telescope', ['stars', 'space', 'zoom', 'science', 'astronomy']],
        ['🔬', 'microscope', ['laboratory', 'experiment', 'zoomin', 'science', 'study']],
        ['🕳', 'hole', ['embarrassing']],
        ['💊', 'pill', ['health', 'medicine', 'doctor', 'pharmacy', 'drug']],
        ['💉', 'syringe', ['health', 'hospital', 'drugs', 'blood', 'medicine', 'needle', 'doctor', 'nurse']],
        ['🧬', 'dna', ['biologist', 'genetics', 'life']],
        ['🦠', 'microbe', ['amoeba', 'bacteria', 'germs']],
        ['🧫', 'petri dish', ['bacteria', 'biology', 'culture', 'lab']],
        ['🧪', 'test tube', ['chemistry', 'experiment', 'lab', 'science']],
        ['🌡', 'thermometer', ['weather', 'temperature', 'hot', 'cold']],
        ['🧹', 'broom', ['cleaning', 'sweeping', 'witch']],
        ['🧺', 'basket', ['laundry']],
        ['🧻', 'toilet paper', ['roll']],
        ['🏷', 'label', ['sale', 'tag']],
        ['🔖', 'bookmark', ['favorite', 'label', 'save']],
        ['🚽', 'toilet', ['restroom', 'wc', 'washroom', 'bathroom', 'potty']],
        ['🚿', 'shower', ['clean', 'water', 'bathroom']],
        ['🛁', 'bathtub', ['clean', 'shower', 'bathroom']],
        ['🧼', 'soap', ['bar', 'bathing', 'cleaning', 'lather']],
        ['🧽', 'sponge', ['absorbing', 'cleaning', 'porous']],
        ['🧴', 'lotion bottle', ['moisturizer', 'sunscreen']],
        ['🔑', 'key', ['lock', 'door', 'password']],
        ['🗝', 'old key', ['lock', 'door', 'password']],
        ['🛋', 'couch and lamp', ['read', 'chill']],
        ['🛌', 'sleeping bed', ['bed', 'rest']],
        ['🛏', 'bed', ['sleep', 'rest']],
        ['🚪', 'door', ['house', 'entry', 'exit']],
        ['🛎', 'bellhop bell', ['service']],
        ['🧸', 'teddy bear', ['plush', 'stuffed']],
        ['🖼', 'framed picture', ['photography']],
        ['🗺', 'world map', ['location', 'direction']],
        ['⛱', 'parasol on ground', ['weather', 'summer']],
        ['🗿', 'moyai', ['rock', 'easter island', 'moai']],
        ['🛍', 'shopping', ['mall', 'buy', 'purchase']],
        ['🛒', 'shopping cart', ['trolley']],
        ['🎈', 'balloon', ['party', 'celebration', 'birthday', 'circus']],
        ['🎏', 'flags', ['fish', 'japanese', 'koinobori', 'carp', 'banner']],
        ['🎀', 'ribbon', ['decoration', 'pink', 'girl', 'bowtie']],
        ['🎁', 'gift', ['present', 'birthday', 'christmas', 'xmas']],
        ['🎊', 'confetti ball', ['festival', 'party', 'birthday', 'circus']],
        ['🎉', 'tada', ['party', 'congratulations', 'birthday', 'magic', 'circus', 'celebration']],
        ['🎎', 'dolls', ['japanese', 'toy', 'kimono']],
        ['🎐', 'wind chime', ['nature', 'ding', 'spring', 'bell']],
        ['🏮', 'izakaya lantern', ['light', 'paper', 'halloween', 'spooky']],
        ['🧧', 'red envelope', ['gift']],
        ['✉️', 'email', ['letter', 'postal', 'inbox', 'communication']],
        ['📩', 'envelope with arrow', ['email', 'communication']],
        ['📨', 'incoming envelope', ['email', 'inbox']],
        ['📧', 'e-mail', ['communication', 'inbox']],
        ['💌', 'love letter', ['email', 'like', 'affection', 'envelope', 'valentines']],
        ['📮', 'postbox', ['email', 'letter', 'envelope']],
        ['📪', 'mailbox closed', ['email', 'communication', 'inbox']],
        ['📫', 'mailbox', ['email', 'inbox', 'communication']],
        ['📬', 'mailbox with mail', ['email', 'inbox', 'communication']],
        ['📭', 'mailbox with no mail', ['email', 'inbox']],
        ['📦', 'package', ['mail', 'gift', 'cardboard', 'box', 'moving']],
        ['📯', 'postal horn', ['instrument', 'music']],
        ['📥', 'inbox tray', ['email', 'documents']],
        ['📤', 'outbox tray', ['inbox', 'email']],
        ['📜', 'scroll', ['documents', 'ancient', 'history', 'paper']],
        ['📃', 'page with curl', ['documents', 'office', 'paper']],
        ['📑', 'bookmark tabs', ['favorite', 'save', 'order', 'tidy']],
        ['🧾', 'receipt', ['accounting', 'expenses']],
        ['📊', 'bar chart', ['graph', 'presentation', 'stats']],
        ['📈', 'chart with upwards trend', ['graph', 'presentation', 'stats', 'recovery', 'business', 'economics', 'money', 'sales', 'good', 'success']],
        ['📉', 'chart with downwards trend', ['graph', 'presentation', 'stats', 'recession', 'business', 'economics', 'money', 'sales', 'bad', 'failure']],
        ['📄', 'page facing up', ['documents', 'office', 'paper', 'information']],
        ['📅', 'date', ['calendar', 'schedule']],
        ['📆', 'calendar', ['schedule', 'date', 'planning']],
        ['🗓', 'spiral calendar', ['date', 'schedule', 'planning']],
        ['📇', 'card index', ['business', 'stationery']],
        ['🗃', 'card file box', ['business', 'stationery']],
        ['🗳', 'ballot box', ['election', 'vote']],
        ['🗄', 'file cabinet', ['filing', 'organizing']],
        ['📋', 'clipboard', ['stationery', 'documents']],
        ['🗒', 'spiral notepad', ['memo', 'stationery']],
        ['📁', 'file folder', ['documents', 'business', 'office']],
        ['📂', 'open file folder', ['documents', 'load']],
        ['🗂', 'card index dividers', ['organizing', 'business', 'stationery']],
        ['🗞', 'newspaper roll', ['press', 'headline']],
        ['📰', 'newspaper', ['press', 'headline']],
        ['📓', 'notebook', ['stationery', 'record', 'notes', 'paper', 'study']],
        ['📕', 'closed book', ['read', 'library', 'knowledge', 'textbook', 'learn']],
        ['📗', 'green book', ['read', 'library', 'knowledge', 'study']],
        ['📘', 'blue book', ['read', 'library', 'knowledge', 'learn', 'study']],
        ['📙', 'orange book', ['read', 'library', 'knowledge', 'textbook', 'study']],
        ['📔', 'notebook with decorative cover', ['classroom', 'notes', 'record', 'paper', 'study']],
        ['📒', 'ledger', ['notes', 'paper']],
    ]) },
    { id: 'symbols', label: 'Symbols', icon: '✅', emoji: entries([
        ['⚠️', 'warning', ['alert', 'caution']],
        ['🆘', 'sos', ['emergency', 'help']],
        ['🌐', 'globe with meridians', ['world', 'internet', 'network']],
        ['📶', 'signal bars', ['radio', 'wireless', 'reception']],
        ['⚡', 'high voltage', ['electric', 'power', 'lightning']],
        ['❤️', 'heart', ['love', 'like', 'valentines']],
        ['🧡', 'orange heart', ['love', 'like', 'affection', 'valentines']],
        ['💛', 'yellow heart', ['love', 'like', 'affection', 'valentines']],
        ['💚', 'green heart', ['love', 'like', 'affection', 'valentines']],
        ['💙', 'blue heart', ['love', 'like', 'affection', 'valentines']],
        ['💜', 'purple heart', ['love', 'like', 'affection', 'valentines']],
        ['🖤', 'black heart', ['evil']],
        ['💔', 'broken heart', ['sad', 'sorry', 'break', 'heart', 'heartbreak']],
        ['❣', 'heavy heart exclamation', ['decoration', 'love']],
        ['💕', 'two hearts', ['love', 'like', 'affection', 'valentines', 'heart']],
        ['💞', 'revolving hearts', ['love', 'like', 'affection', 'valentines']],
        ['💓', 'heartbeat', ['love', 'like', 'affection', 'valentines', 'pink', 'heart']],
        ['💗', 'heartpulse', ['like', 'love', 'affection', 'valentines', 'pink']],
        ['💖', 'sparkling heart', ['love', 'like', 'affection', 'valentines']],
        ['💘', 'cupid', ['love', 'like', 'heart', 'affection', 'valentines']],
        ['💝', 'gift heart', ['love', 'valentines']],
        ['💟', 'heart decoration', ['purple-square', 'love', 'like']],
        ['☮', 'peace symbol', ['hippie']],
        ['✝', 'latin cross', ['christianity']],
        ['☪', 'star and crescent', ['islam']],
        ['🕉', 'om', ['hinduism', 'buddhism', 'sikhism', 'jainism']],
        ['☸', 'wheel of dharma', ['hinduism', 'buddhism', 'sikhism', 'jainism']],
        ['✡', 'star of david', ['judaism']],
        ['🔯', 'six pointed star', ['purple-square', 'religion', 'jewish', 'hexagram']],
        ['🕎', 'menorah', ['hanukkah', 'candles', 'jewish']],
        ['☯', 'yin yang', ['balance']],
        ['☦', 'orthodox cross', ['suppedaneum', 'religion']],
        ['🛐', 'place of worship', ['religion', 'church', 'temple', 'prayer']],
        ['⛎', 'ophiuchus', ['sign', 'purple-square', 'constellation', 'astrology']],
        ['♈', 'aries', ['sign', 'purple-square', 'zodiac', 'astrology']],
        ['♉', 'taurus', ['purple-square', 'sign', 'zodiac', 'astrology']],
        ['♊', 'gemini', ['sign', 'zodiac', 'purple-square', 'astrology']],
        ['♋', 'cancer', ['sign', 'zodiac', 'purple-square', 'astrology']],
        ['♌', 'leo', ['sign', 'purple-square', 'zodiac', 'astrology']],
        ['♍', 'virgo', ['sign', 'zodiac', 'purple-square', 'astrology']],
        ['♎', 'libra', ['sign', 'purple-square', 'zodiac', 'astrology']],
        ['♏', 'scorpius', ['sign', 'zodiac', 'purple-square', 'astrology', 'scorpio']],
        ['♐', 'sagittarius', ['sign', 'zodiac', 'purple-square', 'astrology']],
        ['♑', 'capricorn', ['sign', 'zodiac', 'purple-square', 'astrology']],
        ['♒', 'aquarius', ['sign', 'purple-square', 'zodiac', 'astrology']],
        ['♓', 'pisces', ['purple-square', 'sign', 'zodiac', 'astrology']],
        ['🆔', 'id', ['purple-square', 'words']],
        ['⚛', 'atom symbol', ['science', 'physics', 'chemistry']],
        ['🈳', 'u7a7a', ['kanji', 'japanese', 'chinese', 'empty', 'sky', 'blue-square']],
        ['🈹', 'u5272', ['cut', 'divide', 'chinese', 'kanji', 'pink-square']],
        ['☢', 'radioactive', ['nuclear', 'danger']],
        ['☣', 'biohazard', ['danger']],
        ['📴', 'mobile phone off', ['mute', 'orange-square', 'silence', 'quiet']],
        ['📳', 'vibration mode', ['orange-square', 'phone']],
        ['🈶', 'u6709', ['orange-square', 'chinese', 'have', 'kanji']],
        ['🈚', 'u7121', ['nothing', 'chinese', 'kanji', 'japanese', 'orange-square']],
        ['🈸', 'u7533', ['chinese', 'japanese', 'kanji', 'orange-square']],
        ['🈺', 'u55b6', ['japanese', 'opening hours', 'orange-square']],
        ['🈷️', 'u6708', ['chinese', 'month', 'moon', 'japanese', 'orange-square', 'kanji']],
        ['✴️', 'eight pointed black star', ['orange-square', 'shape', 'polygon']],
        ['🆚', 'vs', ['words', 'orange-square']],
        ['🉑', 'accept', ['ok', 'good', 'chinese', 'kanji', 'agree', 'yes', 'orange-circle']],
        ['💮', 'white flower', ['japanese', 'spring']],
        ['🉐', 'ideograph advantage', ['chinese', 'kanji', 'obtain', 'get', 'circle']],
        ['㊙️', 'secret', ['privacy', 'chinese', 'sshh', 'kanji', 'red-circle']],
        ['🔱', 'trident', ['weapon', 'spear']],
        ['⚜', 'fleur de lis', ['decorative', 'scout']],
        ['〽️', 'part alternation mark', ['graph', 'presentation', 'stats', 'business', 'economics', 'bad']],
        ['🚸', 'children crossing', ['school', 'warning', 'danger', 'sign', 'driving', 'yellow-diamond']],
        ['🔰', 'beginner', ['badge', 'shield']],
        ['♻️', 'recycle', ['arrow', 'environment', 'garbage', 'trash']],
        ['🈯', 'u6307', ['chinese', 'point', 'green-square', 'kanji']],
        ['💹', 'chart', ['green-square', 'graph', 'presentation', 'stats']],
        ['❇️', 'sparkle', ['stars', 'green-square', 'awesome', 'good', 'fireworks']],
        ['✳️', 'eight spoked asterisk', ['star', 'sparkle', 'green-square']],
        ['❎', 'negative squared cross mark', ['x', 'green-square', 'no', 'deny']],
        ['✅', 'white check mark', ['green-square', 'ok', 'agree', 'vote', 'election', 'answer', 'tick']],
        ['💠', 'diamond shape with a dot inside', ['jewel', 'blue', 'gem', 'crystal', 'fancy']],
        ['🌀', 'cyclone', ['weather', 'swirl', 'blue', 'cloud', 'vortex', 'spiral', 'whirlpool', 'spin', 'tornado', 'hurricane', 'typhoon']],
        ['➿', 'loop', ['tape', 'cassette']],
        ['Ⓜ️', 'm', ['alphabet', 'blue-circle', 'letter']],
        ['🏧', 'atm', ['money', 'sales', 'cash', 'blue-square', 'payment', 'bank']],
        ['🈂️', 'sa', ['japanese', 'blue-square', 'katakana']],
        ['🛂', 'passport control', ['custom', 'blue-square']],
        ['🛃', 'customs', ['passport', 'border', 'blue-square']],
        ['🛄', 'baggage claim', ['blue-square', 'airport', 'transport']],
        ['🛅', 'left luggage', ['blue-square', 'travel']],
        ['♿', 'wheelchair', ['blue-square', 'disabled', 'a11y', 'accessibility']],
        ['🚭', 'no smoking', ['cigarette', 'blue-square', 'smell', 'smoke']],
        ['🚾', 'wc', ['toilet', 'restroom', 'blue-square']],
        ['🅿️', 'parking', ['cars', 'blue-square', 'alphabet', 'letter']],
        ['🚰', 'potable water', ['blue-square', 'liquid', 'restroom', 'cleaning', 'faucet']],
        ['🚹', 'mens', ['toilet', 'restroom', 'wc', 'blue-square', 'gender', 'male']],
        ['🚺', 'womens', ['purple-square', 'woman', 'female', 'toilet', 'loo', 'restroom', 'gender']],
        ['🚼', 'baby symbol', ['orange-square', 'child']],
        ['🚻', 'restroom', ['blue-square', 'toilet', 'refresh', 'wc', 'gender']],
        ['🚮', 'put litter in its place', ['blue-square', 'sign', 'human', 'info']],
        ['🎦', 'cinema', ['blue-square', 'record', 'film', 'movie', 'curtain', 'stage', 'theater']],
        ['🈁', 'koko', ['blue-square', 'here', 'katakana', 'japanese', 'destination']],
        ['🆖', 'ng', ['blue-square', 'words', 'shape', 'icon']],
        ['🆗', 'ok', ['good', 'agree', 'yes', 'blue-square']],
        ['🆙', 'up', ['blue-square', 'above', 'high']],
        ['🆒', 'cool', ['words', 'blue-square']],
        ['🆕', 'new', ['blue-square', 'words', 'start']],
        ['🆓', 'free', ['blue-square', 'words']],
        ['0️⃣', 'zero', ['0', 'numbers', 'blue-square', 'null']],
        ['1️⃣', 'one', ['blue-square', 'numbers', '1']],
        ['2️⃣', 'two', ['numbers', '2', 'prime', 'blue-square']],
        ['3️⃣', 'three', ['3', 'numbers', 'prime', 'blue-square']],
        ['4️⃣', 'four', ['4', 'numbers', 'blue-square']],
        ['5️⃣', 'five', ['5', 'numbers', 'blue-square', 'prime']],
        ['6️⃣', 'six', ['6', 'numbers', 'blue-square']],
        ['7️⃣', 'seven', ['7', 'numbers', 'blue-square', 'prime']],
        ['8️⃣', 'eight', ['8', 'blue-square', 'numbers']],
        ['9️⃣', 'nine', ['blue-square', 'numbers', '9']],
        ['🔟', 'keycap ten', ['numbers', '10', 'blue-square']],
        ['*⃣', 'asterisk', ['star', 'keycap']],
        ['🔢', '1234', ['numbers', 'blue-square']],
        ['⏏️', 'eject button', ['blue-square']],
        ['▶️', 'arrow forward', ['blue-square', 'right', 'direction', 'play']],
        ['⏸', 'pause button', ['pause', 'blue-square']],
        ['⏭', 'next track button', ['forward', 'next', 'blue-square']],
        ['⏹', 'stop button', ['blue-square']],
        ['⏺', 'record button', ['blue-square']],
        ['⏯', 'play or pause button', ['blue-square', 'play', 'pause']],
        ['⏮', 'previous track button', ['backward']],
        ['⏩', 'fast forward', ['blue-square', 'play', 'speed', 'continue']],
        ['⏪', 'rewind', ['play', 'blue-square']],
        ['🔀', 'twisted rightwards arrows', ['blue-square', 'shuffle', 'music', 'random']],
        ['🔁', 'repeat', ['loop', 'record']],
        ['🔂', 'repeat one', ['blue-square', 'loop']],
        ['◀️', 'arrow backward', ['blue-square', 'left', 'direction']],
        ['🔼', 'arrow up small', ['blue-square', 'triangle', 'direction', 'point', 'forward', 'top']],
        ['🔽', 'arrow down small', ['blue-square', 'direction', 'bottom']],
        ['⏫', 'arrow double up', ['blue-square', 'direction', 'top']],
        ['⏬', 'arrow double down', ['blue-square', 'direction', 'bottom']],
        ['➡️', 'arrow right', ['blue-square', 'next']],
        ['⬅️', 'arrow left', ['blue-square', 'previous', 'back']],
        ['⬆️', 'arrow up', ['blue-square', 'continue', 'top', 'direction']],
        ['⬇️', 'arrow down', ['blue-square', 'direction', 'bottom']],
        ['↗️', 'arrow upper right', ['blue-square', 'point', 'direction', 'diagonal', 'northeast']],
        ['↘️', 'arrow lower right', ['blue-square', 'direction', 'diagonal', 'southeast']],
        ['↙️', 'arrow lower left', ['blue-square', 'direction', 'diagonal', 'southwest']],
        ['↖️', 'arrow upper left', ['blue-square', 'point', 'direction', 'diagonal', 'northwest']],
        ['↕️', 'arrow up down', ['blue-square', 'direction', 'way', 'vertical']],
        ['↔️', 'left right arrow', ['shape', 'direction', 'horizontal', 'sideways']],
        ['🔄', 'arrows counterclockwise', ['blue-square', 'sync', 'cycle']],
        ['↪️', 'arrow right hook', ['blue-square', 'return', 'rotate', 'direction']],
        ['↩️', 'leftwards arrow with hook', ['back', 'return', 'blue-square', 'undo', 'enter']],
        ['⤴️', 'arrow heading up', ['blue-square', 'direction', 'top']],
        ['⤵️', 'arrow heading down', ['blue-square', 'direction', 'bottom']],
        ['#️⃣', 'hash', ['symbol', 'blue-square', 'twitter']],
        ['ℹ️', 'information source', ['blue-square', 'alphabet', 'letter']],
        ['🔤', 'abc', ['blue-square', 'alphabet']],
    ]) },
    { id: 'flags', label: 'Flags', icon: '🏁', emoji: entries([
        ['🏁', 'chequered flag', ['finish', 'race']],
        ['🚩', 'triangular flag', ['marker']],
        ['🎌', 'crossed flags', ['celebration']],
        ['🏳️', 'white flag', ['surrender']],
        ['🏴', 'black flag', []],
        ['🇺🇸', 'flag united states', ['usa', 'america']],
        ['🇨🇦', 'flag canada', []],
        ['🇲🇽', 'flag mexico', []],
        ['🇧🇷', 'flag brazil', []],
        ['🇬🇧', 'flag united kingdom', ['britain', 'uk']],
        ['🇮🇪', 'flag ireland', []],
        ['🇫🇷', 'flag france', []],
        ['🇩🇪', 'flag germany', []],
        ['🇮🇹', 'flag italy', []],
        ['🇪🇸', 'flag spain', []],
        ['🇵🇹', 'flag portugal', []],
        ['🇳🇱', 'flag netherlands', []],
        ['🇧🇪', 'flag belgium', []],
        ['🇨🇭', 'flag switzerland', []],
        ['🇸🇪', 'flag sweden', []],
        ['🇳🇴', 'flag norway', []],
        ['🇩🇰', 'flag denmark', []],
        ['🇫🇮', 'flag finland', []],
        ['🇵🇱', 'flag poland', []],
        ['🇺🇦', 'flag ukraine', []],
        ['🇯🇵', 'flag japan', []],
        ['🇰🇷', 'flag south korea', []],
        ['🇨🇳', 'flag china', []],
        ['🇮🇳', 'flag india', []],
        ['🇦🇺', 'flag australia', []],
        ['🇳🇿', 'flag new zealand', []],
        ['🇿🇦', 'flag south africa', []],
        ['🇵🇭', 'flag philippines', []],
        ['🇮🇱', 'flag israel', []],
        ['🇪🇺', 'flag european union', ['europe', 'eu']],
        ['🏴‍☠️', 'pirate flag', ['skull', 'crossbones', 'flag', 'banner']],
        ['🇺🇳', 'united nations', ['un', 'flag', 'banner']],
        ['🇦🇫', 'afghanistan', ['af', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇽', 'aland islands', ['åland', 'islands', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇱', 'albania', ['al', 'flag', 'nation', 'country', 'banner']],
        ['🇩🇿', 'algeria', ['dz', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇸', 'american samoa', ['american', 'ws', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇩', 'andorra', ['ad', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇴', 'angola', ['ao', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇮', 'anguilla', ['ai', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇶', 'antarctica', ['aq', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇬', 'antigua barbuda', ['antigua', 'barbuda', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇷', 'argentina', ['ar', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇲', 'armenia', ['am', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇼', 'aruba', ['aw', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇹', 'austria', ['at', 'flag', 'nation', 'country', 'banner']],
        ['🇦🇿', 'azerbaijan', ['az', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇸', 'bahamas', ['bs', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇭', 'bahrain', ['bh', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇩', 'bangladesh', ['bd', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇧', 'barbados', ['bb', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇾', 'belarus', ['by', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇿', 'belize', ['bz', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇯', 'benin', ['bj', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇲', 'bermuda', ['bm', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇹', 'bhutan', ['bt', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇴', 'bolivia', ['bo', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇶', 'caribbean netherlands', ['bonaire', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇦', 'bosnia herzegovina', ['bosnia', 'herzegovina', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇼', 'botswana', ['bw', 'flag', 'nation', 'country', 'banner']],
        ['🇮🇴', 'british indian ocean territory', ['british', 'indian', 'ocean', 'territory', 'flag', 'nation', 'country', 'banner']],
        ['🇻🇬', 'british virgin islands', ['british', 'virgin', 'islands', 'bvi', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇳', 'brunei', ['bn', 'darussalam', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇬', 'bulgaria', ['bg', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇫', 'burkina faso', ['burkina', 'faso', 'flag', 'nation', 'country', 'banner']],
        ['🇧🇮', 'burundi', ['bi', 'flag', 'nation', 'country', 'banner']],
        ['🇨🇻', 'cape verde', ['cabo', 'verde', 'flag', 'nation', 'country', 'banner']],
        ['🇰🇭', 'cambodia', ['kh', 'flag', 'nation', 'country', 'banner']],
        ['🇨🇲', 'cameroon', ['cm', 'flag', 'nation', 'country', 'banner']],
        ['🇮🇨', 'canary islands', ['canary', 'islands', 'flag', 'nation', 'country', 'banner']],
        ['🇰🇾', 'cayman islands', ['cayman', 'islands', 'flag', 'nation', 'country', 'banner']],
        ['🇨🇫', 'central african republic', ['central', 'african', 'republic', 'flag', 'nation', 'country', 'banner']],
        ['🇹🇩', 'chad', ['td', 'flag', 'nation', 'country', 'banner']],
        ['🇨🇱', 'chile', ['flag', 'nation', 'country', 'banner']],
        ['🇨🇽', 'christmas island', ['christmas', 'island', 'flag', 'nation', 'country', 'banner']],
    ]) },
];

export const filterChatEmoji = (categoryId: string, query: string): ChatEmojiEntry[] => {
    const normalizedQuery = query.trim().toLocaleLowerCase();
    const categories = normalizedQuery
        ? CHAT_EMOJI_CATEGORIES
        : CHAT_EMOJI_CATEGORIES.filter(category => category.id === categoryId);
    return categories.flatMap(category => category.emoji)
        .filter(entry => !normalizedQuery || entry.name.includes(normalizedQuery)
            || entry.keywords.some(keyword => keyword.includes(normalizedQuery))
            || entry.emoji === normalizedQuery);
};

export const insertChatEmoji = (
    value: string, selectionStart: number, selectionEnd: number, emoji: string
): { value: string; caret: number } => ({
    value: `${value.slice(0, selectionStart)}${emoji}${value.slice(selectionEnd)}`,
    caret: selectionStart + emoji.length
});
